### ISSUE TITLE
Scaffold project structure

### ISSUE THREAD

**Issue by benedyktdryl** [benedyktdryl/junior-training-app#5]
Propose in comments and scaffold project structure (directories/files).

**Comment by Txwxcc** [comment]
Are we going to use CSS preprocessor?

**Comment by benedyktdryl** [comment]
@Txwxcc Yes - we will use SASS.

**Comment by Txwxcc** [comment]
I think

- **css/** *for sass/scss/less*
- **src/** *for js*
- **dist/** *root dir for page*

ie.
-- css/main.scss
-- src/main.js
-- dist/index.html
-- dist/main.js *sass output*
-- dist/main.css *js bundle*
